### ISSUE TITLE
Can `rlib` be added to `crate-type`?

### ISSUE THREAD

**Issue by jquesada2016** [surrealdb/surrealdb.wasm#10]
I wanted to try and play around with the crate from within another WASM rust crate, but I can't import anything because the crate isn't being compiled as a rust library.

Currently:
```toml
[lib]
crate-type = ["cdylib"]
```

Could be changed to:
```toml
[lib]
crate-type = ["cdylib", "rlib"]
```
